### ISSUE TITLE
Value conversion error for fields 

### ISSUE THREAD

**Issue by yadavnikhil** [appscode/chartify#17]
Hi

I am evaluating your code to convert my kubernetes yml to helm.
Working good, but few issues:
1. When converting, for Deployment Template spec, in ImagePullSecrets, in the output file, the "name" is converted to "Name". "n" to uppercase: for which helm fails.
imagePullSecrets:
      - Name: my-pull-secret

I've few more issues, which i was able to fix in my local fork. 

Is this repo still active? i will open a PR for few changes.

**Comment by tamalsaha** [comment]
Yes, this repo is active. Please file your pr.

**Comment by yadavnikhil** [comment]
Ok great, Thanks.
Can you please answer for the issue:
"name" is converted to "Name". "n" to uppercase: for which helm fails.

**Comment by tamalsaha** [comment]
Can you be more specific? Can you point to code or YAML sample?

**Comment by yadavnikhil** [comment]
This is my deployment.yml, secret.yml:
```yaml
apiVersion: extensions/v1beta1 
kind: Deployment
metadata:
  name: nginx-deployment
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: myregistry:5000/nginx:1.7.9
        ports:
        - containerPort: 80
      imagePullSecrets:
      - name: my-pull-secret

apiVersion: v1
kind: Secret
metadata:
  name: my-pull-secret
data:
  .dockerconfigjson: <token>
type: kubernetes.io/dockerconfigjson
```

Below is my output: nginx-deployment.deployment.yaml

```yaml
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    chart: '{{.Chart.Name}}-{{.Chart.Version}}'
    heritage: '{{.Release.Service}}'
    release: '{{.Release.Name}}'
  name: '{{ template "fullname" . }}-nginx-deployment'
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - image: '{{.Values.nginxdeployment.nginx.image}}:{{.Values.nginxdeployment.nginx.imageTag}}'
        name: nginx
        ports:
        - containerPort: 80
      imagePullSecrets:
      - Name: my-pull-secret
```

As you see above, for imagePullSecrets, the field "Name" --> "N" is in uppercase.
